service {
    cluster-name deepops
    proto-fd-max 15000
}

logging {
    console {
        context any info
    }
}

network {
    service {
        address any
        port 3000
    }

    heartbeat {
        mode mesh
        port 3002
        interval 150
        timeout 10
    }

    fabric {
        port 3001
    }
}

namespace deepops {
    replication-factor 1
    default-ttl 0
    stop-writes-sys-memory-pct 90
    evict-indexes-memory-pct 80

    storage-engine device {
        file /opt/aerospike/data/deepops.dat
        filesize 4G
        evict-used-pct 70
    }
}
